### ISSUE TITLE
Source node without an explicit "left"/"top" would not align correctly

### ISSUE THREAD

**Issue by mooncakelmn** [yiminghe/dom-align#2]
I agree the source node is **good** to have an initial "left/top" set (i.e "-9999px"), to shown out of screen before we calculated the actual position. However, not all developers doing **good** things. 

Debugging into the source, the issue happens in `utils.setOffset`, `current` is always `0` if the initial "left/top" are not set.

```JavaScript
...
for (key in offset) {
  current = parseFloat(css(elem, key)) || 0;
  ret[key] = current + offset[key] - old[key];
}
...
```
BTW, I'm from China, to keep consistent with your repo style, I'm using English instead. And this tool is cool :yum:

**Comment by yiminghe** [comment]
good idea
