### ISSUE TITLE
Setting OverflowX is not adjusting source onto screen

### ISSUE THREAD

**Issue by gcoombe** [yiminghe/dom-align#21]
See demo here:

http://requirebin.com/?gist=1406e9992ca56949d224903c2f87c11a

My understanding of setting overflow: {adjustX: true}  is that if the source is positioned offscreen it should be adjusted back onto the screen

As seen in the provided example this does  not seem to be happening.

It seems like this was a regression caused by this commit: https://github.com/yiminghe/dom-align/commit/aaac734c280ea70c1f2c9e086a9ce3bdee3169f3 .  Specifically

```js
newOverflowCfg.adjustX = overflow.adjustX &&
      isFailX(elFuturePos, elRegion, realXRegion);
```

Should be 

```js
newOverflowCfg.adjustX = overflow.adjustX &&
      isFailX(elFuturePos, elRegion, visibleRect);
```

**Comment by benjycui** [comment]
I don't understand, could your provide more info?

**Comment by benjycui** [comment]
Close for no response.
