### ISSUE TITLE
Menu有问题

### ISSUE THREAD

**Issue by ityao** [yiminghe/dom-align#28]
使用最新的SiderMenu后出现这个问题, 源码例子测试没有这个问题, 所以不知道怎么处理, 请教一下!
Menu Collapsed 之后二级菜单没有变成弹出框, 而是保持原来的下拉框, 是什么情况呢

![image](https://user-images.githubusercontent.com/832215/33998025-413ddab0-e121-11e7-9494-19cb626df537.png)

**Comment by benjycui** [comment]
Please file your issue in ant-design/
