### ISSUE TITLE
The returned object lacks width and height properties in ie8

### ISSUE THREAD

**Issue by guxingke201** [yiminghe/dom-align#30]
ie8下有兼容性问题：
https://caniuse.com/#search=getBoundingClientRect
The returned object lacks width and height properties.

**Comment by benjycui** [comment]
https://github.com/yiminghe/dom-align/blob/fe09cecae7714bc7cca9fbf29413849f3db1ebaf/src/utils.js#L46

**Comment by guxingke201** [comment]
ie8 下是支持getBoundingClientRect ，但只是部分支持，高度已经亲测有问题，获取不到，一直是0
