### ISSUE TITLE
ie8 下是支持getBoundingClientRect ，但只是部分支持，高度已经亲测有问题，获取不到，一直是0

### ISSUE THREAD

**Issue by guxingke201** [yiminghe/dom-align#31]
最终ie8下会出现如下现象：
![image](https://user-images.githubusercontent.com/8326941/34979812-71fd0fb0-fadd-11e7-8745-8459005feb21.png)
期望：能和Feature描述中的一致
![image](https://user-images.githubusercontent.com/8326941/34979899-b889ffe2-fadd-11e7-89c1-3c5087f48b18.png)

**Comment by benjycui** [comment]
已放弃 IE8，README.md 已更新 https://github.com/yiminghe/dom-align/commit/b504caa407b23d29d9029014392b73e83d657df4
