### ISSUE TITLE
container 元素 position: sticky 时候, getBoundingClientRect 返回值可能会不对

### ISSUE THREAD

**Issue by evantre** [yiminghe/dom-align#32]
chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=672457

https://jsfiddle.net/haLz537b/

**Comment by benjycui** [comment]
Please provide re-producible demo.

**Comment by evantre** [comment]
https://github.com/evantre/pos-demo 可以看这个 demo，用最新版本 electron 打开可以看到 dropdown 的 menu 位置不对

**Comment by benjycui** [comment]
这个用 CodeSandbox 之类的线上 demo 会比较好，本地没装 electron。

**Comment by evantre** [comment]
CodeSandbox 貌似改不了浏览器版本吧，这个 bug 只有在稍微有点旧的 chrome 才会出现，比如electron用的

git clone https://github.com/electron/electron-quick-start
npm install && npm start

把代码里面的地址改成 demo 的地址就可以了

**Comment by benjycui** [comment]
太老的 Chrome 不考虑支持，Chrome 的升级机制确定了老版本只是极少数。
