### ISSUE TITLE
Usage With Elements Within Shadow Dom

### ISSUE THREAD

**Issue by kaufmann42** [yiminghe/dom-align#33]
I am using the antd library for my UI (located within a shadow dom in an Google Chrome Extension) and have been experiencing issues when using the Popover component. I've traced the error back to the use of this library when trying to work with document fragments, which breaks the flow.

Any advice on this?

**Comment by benjycui** [comment]
Please provide re-producible demo.

**Comment by kaufmann42** [comment]
https://codesandbox.io/s/14mj6mz4jj

**Comment by benjycui** [comment]
Yep, dom-align doesn't work with ShadowRoot.

But I am busy with other project now, and this issue need lots of time to fix, so I am sorry about that I cannot fix it recently.

You can try to fix it, or wait.

**Comment by soguagirl** [comment]
https://codesandbox.io/s/cranky-snyder-h6gc3

加了2个try catch，可以解。
没仔细测，测了一个Popover没问题的

**Comment by israelfloresdga** [comment]
I'm also using Ant'd with Vue and then wrapping the vue component to a WebComponent. I edited the function as follow

```js
function _getComputedStyle(elem, name, cs) {
  var computedStyle = cs;
  var val = '';
  var d = getDocument(elem);
  if(elem.nodeType === 11) {
    computedStyle = computedStyle || d.defaultView.getComputedStyle(elem.lastElementChild, null);
  }
  else{
    computedStyle = computedStyle || d.defaultView.getComputedStyle(elem, null);
  }
  if (computedStyle) {
    val = computedStyle.getPropertyValue(name) || computedStyle[name];
  }
  return val;
}
```
