### ISSUE TITLE
是否有比较合理的方式可以在外层判断是否经过了adjust?

### ISSUE THREAD

**Issue by dongmei761** [yiminghe/dom-align#5]
您好，我的问题是，如果dom-align后对target node进行了调整，在外面怎么才能确定确实经过了adjust呢？目前domAlign方法的返回值里有point、offset和targetoffset，我想的是可以根据这几个值是否经过flipOffset处理过来判断是否经过了adjust，但这样的方式感觉不够直观，请问是否有其他方式来进行这种判断呢？
或者把fail也返回？

**Comment by yiminghe** [comment]
en, failX failY 也返回吧，你提个 pr 看看

**Comment by dongmei761** [comment]
好的，多谢哦～

**Comment by Tronside** [comment]
您好， 我有有个问题    关于自定义模板，淘宝装修店铺那块开发，鼠标隔着遮罩层 来识别是否停留在遮罩层下面Iframe内某dom元素上的方法是不是通过elementFromPoint来实现的？ 最近在做一个相关的项目，想确认下，或者有更好的方法？  如果不是描述的很清楚  可以看下我找到的一篇相关的内容 https://github.com/Tronside/Tech-loading/issues/1，望回复
